version: '3.8'

services:
  triton:
    container_name: triton
    build:
      context: .
      dockerfile: dockerfiles/Triton.Dockerfile
    ports:
      - 8000:8000 # HTTP endpoints for inference
      - 8001:8001 # GRPS endpoints for inference
      - 8002:8002 # Metrics endpoints for Prometheus
    restart: always
    volumes:
      - ./triton/models:/models
    command: ["tritonserver", "--model-store=/models"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: 1

  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: dockerfiles/Caddy.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
