version: '3.8'

services:
  triton:
    container_name: triton
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.triton
    ports:
      - 8000:8000 # HTTP endpoints for inference
      - 8001:8001 # GRPS endpoints for inference
      - 8002:8002 # Metrics endpoints for Prometheus
    restart: always
    volumes:
      - ./triton/models:/models
    command: ["tritonserver", "--model-store=/models"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: 1

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: dockerfiles/Dockerfile.backend
    restart: always
    depends_on:
      - postgres

  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.caddy
    ports:
      - 80:80
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
