version: '3.8'

services:
  triton:
    container_name: triton
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    ports:
      - 8000:8000 # HTTP endpoints for inference
      - 8001:8001 # GRPS endpoints for inference
      - 8002:8002 # Metrics endpoints for Prometheus
    restart: always
    volumes:
      - ./triton/models:/models
    command: ["tritonserver", "--model-store=/models"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1
