syntax = "proto3";

package inference.v1.api;

option go_package = "audio-inference-service/gen/inference/v1;inferencev1";

service InferenceService {
  rpc CreateTask(CreateTaskRequest) returns (CreateTaskResponse);
  rpc GetTask(GetTaskRequest) returns (GetTaskResponse);
}

message CreateTaskRequest {
  bytes audio_file = 1;
  string filename = 2;
  string model_name = 3;
}

message CreateTaskResponse {
  Task task = 1;
}

message GetTaskRequest {
  string task_id = 1;
}

message GetTaskResponse {
  Task task = 1;
}

message Task {
  string task_id = 1;
  TaskStatus status = 2;
  string model = 3;
  TaskResult result = 4;
}

message TaskResult {
  string filename = 1;
  repeated Chunk chunks = 2;
}

message Chunk {
  int32 chunk_index = 1;
  int32 layer = 2;
  int32 offset = 3;
  repeated float category = 4;
  repeated float target = 5;
  string error_message = 6;
}

enum TaskStatus {
  STATUS_UNSPECIFIED = 0;
  STATUS_SUCCESS = 1;
  STATUS_FAILURE = 2;
  STATUS_PENDING = 3;
  STATUS_PROCESSING = 4;
}
