name: "torch_audio_cnn"
backend: "onnxruntime"
max_batch_size: 1

default_model_filename: "cnn_model.onnx"

input [
    {
        name: "input"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [ 1, 256, 173 ]
    }
]

output [
    {
        name: "category_output"
        data_type: TYPE_FP32
        dims: [ 5 ]
    },
    {
        name: "target_output"
        data_type: TYPE_FP32
        dims: [ 7 ]
    }
]